extends:
  - eslint:recommended
  - plugin:vue/base
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: [error, 2]
  quotes: [warn, single]
  semi: [error, never]
  block-spacing: [error, always]
  func-call-spacing: [error, never]
  object-curly-spacing:
    [warn, always, { arraysInObjects: false, objectsInObjects: false }]
  keyword-spacing: [warn, { before: true, after: true }]
  key-spacing: [warn, { beforeColon: false, afterColon: true, mode: strict }]
  space-in-parens: [warn, never]
  space-infix-ops: [error, { int32Hint: true }]
  arrow-spacing: [error, { before: true, after: true }]
  no-multi-spaces: [error]
  vue/this-in-template: [warn, never]
  vue/order-in-components:
    [
      error,
      order:
        [
          el,
          name,
          data,
          components,
          computed,
          [props, propsData],
          methods,
          watch,
          model,
          setup,
        ],
    ]
  vue/v-on-style: [warn, shorthand]
  vue/html-closing-bracket-newline:
    [error, { singleline: never, multiline: never }]
  vue/html-indent: [error, 2]
